version: '3'
services:
  app:
    #container_name: center
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./images:/app/images
    networks:
      - center
  
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/app
    networks:
      - center
    
networks:
  center:
