version: '3'
services:
  app:
    container_name: center
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./images:/app/images
    networks:
      - center
    
networks:
  center:
